[project]
name = "gemma3-multilingual-translator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.10.1",
    "bitsandbytes>=0.48.1",
    "datasets>=4.2.0",
    "evaluate>=0.4.6",
    "huggingface-hub>=0.35.3",
    "ipykernel>=7.0.1",
    "matplotlib>=3.10.7",
    "onnx>=1.17.0",
    "onnx-ir>=0.1.11",
    "onnxruntime>=1.23.1",
    "peft>=0.17.1",
    "protobuf==3.20.3",
    "python-dotenv>=1.1.1",
    "sentencepiece>=0.2.1",
    "tensorboard>=2.20.0",
    "torch>=2.9.0",
    "transformers==4.55.4",
    "trl>=0.22.2",
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
torch = [
  { index = "pytorch-cu128", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
  { index = "pytorch-cu128", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

